### ISSUE TITLE
letting stdout from sbot through to parent?

### ISSUE THREAD

**Issue by ralphtheninja** [ralphtheninja/sbot-test-guard#9]
@pfraze It's very silent when running the guard. Should we let through stdout from the child?

**Comment by pfrazee** [comment]
Yeah I think that's a good idea. Their output might overlap in weird ways -- but let's try it.

**Comment by ralphtheninja** [comment]
@pfraze What do you think about this format?

![screenshot from 2015-02-09 23 43 33](https://cloud.githubusercontent.com/assets/308049/6117541/8022b5c4-b0b5-11e4-959f-2d17e8fbb207.png)

Might not be the prettiest, but inverting the text helps (humans) a lot with separating data from the two processes.

**Comment by pfrazee** [comment]
@ralphtheninja oh yeah I like that. :+1:

**Comment by ralphtheninja** [comment]
This is what the errors look like and when the guard ends execution after too many crashes:

![screenshot from 2015-02-10 00 13 27](https://cloud.githubusercontent.com/assets/308049/6118032/bd9b6136-b0b9-11e4-82d4-0ecf5448f51f.png)

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ sbot-test-guard@3.1.0
```
